"""
Run a task that produces an HTML report, then pull reports back to the client and write them
to local files.

The tasks enable reports with ``@env.task(report=True)`` and write HTML into the report using
``flyte.report``. After the run finishes:

- ``run.get_report()`` fetches the report for the run's *root* action.
- ``Action.get_report()`` fetches the report for a *specific action* nested inside the run
  (e.g. a child task invoked by the root task). You can locate that action with
  ``flyte.remote.Action.listall(for_run_name=...)`` or ``flyte.remote.Action.get(...)``.

In both cases the SDK asks the data proxy for a signed download link for the report artifact,
downloads it, and returns the HTML as a string.
"""

import os
from pathlib import Path

import flyte
import flyte.report
from flyte.remote import Action

env = flyte.TaskEnvironment(
    name="get-report-env",
    resources=flyte.Resources(memory="500Mi", cpu=1),
    image=flyte.Image.from_debian_base(),
)


@env.task(report=True)
async def child_report(name: str) -> str:
    """A child action that writes its own HTML report."""
    tab = flyte.report.get_tab("Child")
    tab.log(f"<h1>Child report for {name}</h1>")
    tab.log("<p>This report belongs to a child action inside the run.</p>")
    await flyte.report.flush.aio()
    return f"child:{name}"


@env.task(report=True)
async def make_report(name: str) -> str:
    """Write the root action's HTML report and invoke a child action that writes its own."""
    tab = flyte.report.get_tab("Greeting")
    tab.log(f"<h1>Hello, {name}!</h1>")
    tab.log("<p>This report was generated by the root action of the run.</p>")
    await flyte.report.flush.aio()

    await child_report(name)
    return f"Hello, {name}!"


if __name__ == "__main__":
    flyte.init_from_config(os.environ.get("FLYTE_CONFIG"))

    run = flyte.run(make_report, name="world")
    print(f"Execution URL: {run.url}")

    # Block until the run reaches a terminal state so the reports have been flushed to storage.
    run.wait()

    # 1. Pull the root action's report and write it to a local file.
    root_report_html = run.get_report()
    root_output_path = Path("report.html")
    root_output_path.write_text(root_report_html)
    print(f"Root action report written to {root_output_path.resolve()}")

    # 2. Pull a report from a specific action nested inside the run. Here we find the child
    #    action by its task name; you could also match on the action name or phase.
    for action in Action.listall(for_run_name=run.name):
        if action.task_name == child_report.name:
            child_report_html = action.get_report()
            child_output_path = Path("child_report.html")
            child_output_path.write_text(child_report_html)
            print(f"Child action '{action.name}' report written to {child_output_path.resolve()}")
            break
    else:
        print("No child action report found.")
